language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  # Test compiling ts
  - npm run build
  # Run tests
  - npm test
  # - npm run coveralls
